// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailProcurement.WebAPI.Persistence;

#nullable disable

namespace RetailProcurement.WebAPI.Migrations
{
    [DbContext(typeof(RetailProcurementDbContext))]
    [Migration("20240128131403_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.OrderItemSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierStoreItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierStoreItemId");

                    b.ToTable("OrderItemSupplier", (string)null);
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.QuarterlyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("QuarterlyPlans", (string)null);
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.StoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("StoreItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Soap"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tuna"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Table"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Tuna"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Sausages"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Towels"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Chips"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Towels"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Chips"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Chips"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Table"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Soap"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Chips"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Table"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Bike"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Hat"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Tuna"
                        });
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Turcotte, Toy and Welch"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Turcotte - Nicolas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hoeger, Klocko and Greenholt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nader Group"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lueilwitz - Simonis"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blick, Waelchi and Gutkowski"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Parisian, Flatley and Volkman"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Harber - McKenzie"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rippin - Bergstrom"
                        },
                        new
                        {
                            Id = 10,
                            Name = "West Group"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Muller, Schuster and Lubowitz"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Maggio, Hagenes and Homenick"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mante - Walsh"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mraz - Gutmann"
                        },
                        new
                        {
                            Id = 15,
                            Name = "White Inc"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hyatt LLC"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Crona, Schuster and Osinski"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Stiedemann and Sons"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Champlin - Volkman"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Buckridge Group"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Goyette, Powlowski and Auer"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Kuhic, Bogisich and Marvin"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Von LLC"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Nicolas, VonRueden and Toy"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Abbott, Heaney and Marvin"
                        },
                        new
                        {
                            Id = 26,
                            Name = "MacGyver - McCullough"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Leannon - Wisoky"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Runolfsson - Farrell"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Simonis, Emmerich and Bernhard"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Kutch, Bradtke and Murray"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Wisozk, Gutmann and Klein"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Jaskolski, Kreiger and Lubowitz"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Wilkinson and Sons"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Legros, Mertz and Howe"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Bode, Cormier and Adams"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Corwin - Wiegand"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Weber Group"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Stoltenberg - Waters"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Hane - Sporer"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Prosacco - Anderson"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Grimes - Von"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ernser Group"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Hand - Wolf"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Schuster, Abshire and Macejkovic"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Lind, Deckow and Toy"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ankunding, Koelpin and Leffler"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Lueilwitz LLC"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Pfeffer, O'Connell and Marks"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Hills and Sons"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Goldner - Weber"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Cormier, Lynch and Spencer"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Nikolaus - Blanda"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Rath LLC"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Bednar, Feeney and Schmitt"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Harvey - Marquardt"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Baumbach - Donnelly"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Weber Inc"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Pfeffer - Stiedemann"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Hoppe - Huels"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Sipes and Sons"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Morar - Dietrich"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Lowe and Sons"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Wiegand - Kozey"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Stamm, Botsford and Haley"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Herzog Inc"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Schultz, Wiza and Dooley"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Beatty LLC"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Gulgowski, Rippin and Conroy"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Rohan Inc"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Corwin, Morissette and Buckridge"
                        },
                        new
                        {
                            Id = 71,
                            Name = "McLaughlin, Marquardt and Schuppe"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Barrows - Wehner"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Towne - Beier"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Balistreri, Robel and Murazik"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Waelchi - Mraz"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Ortiz - Rodriguez"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Dietrich LLC"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Schulist, Heidenreich and Bode"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Fisher LLC"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Hintz LLC"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Emmerich, Swift and Barton"
                        },
                        new
                        {
                            Id = 82,
                            Name = "White Group"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Cole Group"
                        },
                        new
                        {
                            Id = 84,
                            Name = "D'Amore, Witting and Nikolaus"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Gutkowski, Gulgowski and Satterfield"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Casper, Haag and Ward"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Walker - Prohaska"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Lueilwitz LLC"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Wintheiser, Trantow and White"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Orn, Reilly and Goldner"
                        },
                        new
                        {
                            Id = 91,
                            Name = "McCullough - Gerhold"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Ruecker, Beatty and Lang"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Gerhold - Russel"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Cassin, Bailey and Tillman"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Vandervort - Powlowski"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Muller LLC"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Hills Group"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Brakus LLC"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Dibbert - Ritchie"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Rodriguez - Grant"
                        });
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.SupplierStoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StoreItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("StoreItemId", "SupplierId");

                    b.ToTable("SupplierStoreItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 0m,
                            StoreItemId = 79,
                            SupplierId = 80
                        },
                        new
                        {
                            Id = 2,
                            Price = 0m,
                            StoreItemId = 34,
                            SupplierId = 15
                        },
                        new
                        {
                            Id = 3,
                            Price = 0m,
                            StoreItemId = 41,
                            SupplierId = 47
                        },
                        new
                        {
                            Id = 4,
                            Price = 0m,
                            StoreItemId = 47,
                            SupplierId = 81
                        },
                        new
                        {
                            Id = 5,
                            Price = 0m,
                            StoreItemId = 57,
                            SupplierId = 36
                        },
                        new
                        {
                            Id = 6,
                            Price = 0m,
                            StoreItemId = 42,
                            SupplierId = 75
                        },
                        new
                        {
                            Id = 7,
                            Price = 0m,
                            StoreItemId = 92,
                            SupplierId = 25
                        },
                        new
                        {
                            Id = 8,
                            Price = 0m,
                            StoreItemId = 72,
                            SupplierId = 64
                        },
                        new
                        {
                            Id = 9,
                            Price = 0m,
                            StoreItemId = 48,
                            SupplierId = 47
                        },
                        new
                        {
                            Id = 10,
                            Price = 0m,
                            StoreItemId = 41,
                            SupplierId = 62
                        });
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.Order", b =>
                {
                    b.HasOne("RetailProcurement.WebAPI.Entities.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.OrderItemSupplier", b =>
                {
                    b.HasOne("RetailProcurement.WebAPI.Entities.Order", "Order")
                        .WithMany("OrderItemSuppliers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("RetailProcurement.WebAPI.Entities.Supplier", null)
                        .WithMany("OrderItemSuppliers")
                        .HasForeignKey("SupplierId");

                    b.HasOne("RetailProcurement.WebAPI.Entities.SupplierStoreItem", "SupplierStoreItem")
                        .WithMany("OrderItemSuppliers")
                        .HasForeignKey("SupplierStoreItemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SupplierStoreItem");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.QuarterlyPlan", b =>
                {
                    b.HasOne("RetailProcurement.WebAPI.Entities.Supplier", "Supplier")
                        .WithMany("QuarterlyPlans")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.SupplierStoreItem", b =>
                {
                    b.HasOne("RetailProcurement.WebAPI.Entities.StoreItem", "StoreItem")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("RetailProcurement.WebAPI.Entities.Supplier", "Supplier")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.Order", b =>
                {
                    b.Navigation("OrderItemSuppliers");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.StoreItem", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.Supplier", b =>
                {
                    b.Navigation("OrderItemSuppliers");

                    b.Navigation("Orders");

                    b.Navigation("QuarterlyPlans");

                    b.Navigation("SupplierStoreItems");
                });

            modelBuilder.Entity("RetailProcurement.WebAPI.Entities.SupplierStoreItem", b =>
                {
                    b.Navigation("OrderItemSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
